## our modules are without the "lib" prefix

MACRO(ADD_AND_INSTALL_LIBRARY LIBNAME SRCFILES)
  IF(BUILD_STATIC)
    ADD_LIBRARY(${LIBNAME} STATIC ${SRCFILES})
    TARGET_LINK_LIBRARIES(lighttpd ${LIBNAME})
  ELSE(BUILD_STATIC)
    ADD_LIBRARY(${LIBNAME} SHARED ${SRCFILES})
    SET(L_INSTALL_TARGETS ${L_INSTALL_TARGETS} ${LIBNAME})
    ## Windows likes to link it thisway back to app!
    IF(WIN32)
        SET_TARGET_PROPERTIES(${LIBNAME} PROPERTIES LINK_FLAGS lighttpd.lib)
    ENDIF(WIN32)
  ENDIF(BUILD_STATIC)
ENDMACRO(ADD_AND_INSTALL_LIBRARY)

MACRO(LEMON_PARSER SRCFILE)
  GET_FILENAME_COMPONENT(SRCBASE ${SRCFILE} NAME_WE)
  ADD_CUSTOM_COMMAND(OUTPUT ${SRCBASE}.c 
  COMMAND ${CMAKE_CURRENT_BINARY_DIR}/lemon
  ARGS ${SRCFILE}
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  COMMENT "Generating ${SRCBASE}.c from ${SRCFILE}"
)
ENDMACRO(LEMON_PARSER)